### ISSUE TITLE
Nothing happens

### ISSUE THREAD

**Issue by philshil** [mpellegrin/nagios-eventhandler-cachet#5]
Hello,
i have downloaded the files, edited the cachet_notify file with the address and API key.
i can manually force it to add a new incident using ;
/cachet_notify 'Insight' 'PSH' CRITICAL HARD 'The service is Critical'

however when i add event_handler          cachet_notify!Insight nothing happens.

**Comment by dpina000** [comment]
Hi,

Possible errors:

1) Do you have a cachet component called "Insight" ? Because that's what you'r parsing into cachet, and if there is a mistype nothing will happen.

2) Your event_handler is only called when the service goes down on nagios. Can you check on your nagios logs that the service X where you added the event_handler did in fact go down?

**Comment by philshil** [comment]
okay,
i think i have found the issue 
1450777352] wproc:   stderr line 01: execvp(/usr/share/nagios3/plugins/eventhandlers/cachet_notify, ...) failed. errno is 2: No such file or directory

i can't find where to change to point it to the correct directory :/

**Comment by dpina000** [comment]
You've configured the command as per the instructions most likely, so these lines should be in your config files:

define command {
      command_name    cachet_notify
      command_line    /usr/share/nagios3/plugins/eventhandlers/cachet_notify '$ARG1$' '$SERVICEDESC$' '$SERVICESTATE$' '$SERVICESTATETYPE$' '$SERVICEOUTPUT$'
  }

you can change the path there from /usr/share/nagios3/plugins/eventhandlers/ to something else.

**Comment by philshil** [comment]
Its posted now, hasn't changed the status but has created an incident thanks :+1:
